spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 #日期序列化走北京时间
    default-property-inclusion: non_null #对json数据进行批量配置使返回的数据不为空
server:
  context-path: /sell